"""Extract numeric constants from Python's constants.py and emit R source code
that builds the equivalent nested-list structure used by the BSSUnfold R package.

The output `constants_data.R` is sourced at package load time (from R/onload.R
or directly assigned by sysdata generation) so all functions can rely on the
same numeric values as the upstream Python package.
"""
from __future__ import annotations

import importlib.util
import math
import sys
from pathlib import Path

PY_CONST = Path("/home/z/my-project/bssunfold/src/bssunfold/constants.py")
R_OUT = Path("/home/z/my-project/bssunfoldr/R/constants_data.R")


def _load_module(path: Path):
    spec = importlib.util.spec_from_file_location("bssunfold_constants", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _emit_value(v, depth: int = 1) -> str:
    indent = "  " * depth
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        if isinstance(v, float):
            if math.isnan(v):
                return "NA_real_"
            if math.isinf(v):
                return "Inf" if v > 0 else "-Inf"
        # Use repr to preserve full precision; R accepts 1e-09 etc.
        return repr(float(v))
    if isinstance(v, list):
        if not v:
            return "NULL"
        inner = ",\n".join(f"{indent}{_emit_value(x, depth + 1)}" for x in v)
        return f"c(\n{inner}\n{'  ' * (depth - 1)})"
    if isinstance(v, dict):
        if not v:
            return "list()"
        items = [f"{indent}{k!r} = {_emit_value(val, depth + 1)}" for k, val in v.items()]
        inner = ",\n".join(items)
        return f"list(\n{inner}\n{'  ' * (depth - 1)})"
    raise TypeError(f"Unsupported type for value: {type(v).__name__}")


def main() -> None:
    mod = _load_module(PY_CONST)
    names = [
        "ICRP116_COEFF_EFFECTIVE_DOSE",
        "ICRP74_COEFF_EFFECTIVE_DOSE",
        "NRB99_2009_COEFF_EFFECTIVE_DOSE",
        "ICRP74_COEFF_OPERATIONAL_QUANTITIES",
        "RF_GSF",
        "RF_PTB",
        "RF_LANL",
        "RF_JINR",
        "RF_FERMILAB",
        "RF_EURADOS",
        "RF_IHEP",
    ]
    out_lines = [
        "# Generated by scripts/extract_constants_to_r.py --- DO NOT EDIT BY HAND.",
        "# Numeric values are copied verbatim from the Python bssunfold package",
        "# (src/bssunfold/constants.py) so that the R port reproduces the same",
        "# ICRP-74/116 / NRB99 / response-function data.",
        "",
        ".BSSUNFOLD_CONSTANTS <- list(",
    ]
    items = []
    for n in names:
        if not hasattr(mod, n):
            print(f"WARN: {n} missing in constants.py", file=sys.stderr)
            continue
        v = getattr(mod, n)
        items.append(f"  {n} = {_emit_value(v, depth=2)}")
    out_lines.append(",\n".join(items))
    out_lines.append(")")
    out_lines.append("")
    R_OUT.parent.mkdir(parents=True, exist_ok=True)
    R_OUT.write_text("\n".join(out_lines), encoding="utf-8")
    size_kb = R_OUT.stat().st_size / 1024
    print(f"Wrote {R_OUT} ({size_kb:.1f} KB, {len(out_lines)} lines)")


if __name__ == "__main__":
    main()
